### PR TITLE
Timing in nop for Amstrad CPC

### PR DESCRIPTION
**Pull request by IIIvan37**
Timing in nop for Amstrad CPC

- Timing added in nops for each mnemonics
- mnemonics are sorted

### CODE REVIEW

**Comment by theNestruo** [comment]
Thanks! Extension updated and published.
I'm not a CPC coder myself; can you provide me some background info on how Amstrad CPC timing in NOPs works, to properly describe it in the readme file?

**Comment by IIIvan37** [comment]
Hi,


CPC stretches parts of instructions so they always take multiples of 4-states.
All my timings comes from Rasm documentation.

Also, they’re some missing instructions like out (c), 0, etc…


Good job on the extension and thanks for the merge, glad If if can contribute :)

**Comment by theNestruo** [comment]
Thank you!

I'll talk to map.grauw.nl page mantainer about the missing instructions (do you happen to have a complete list of what is missing?)

Also, I've been reviewing the RASM documentation, and I'm afraid some of its shorcuts are not supported by this extension (`push hl,de,bc`, `ld hl,bc`, etc.). I hope it's not a problem for you!

**Comment by IIIvan37** [comment]
Hi,

Not a problem, maybe I can add Rasm specific instructions ?
I’ll send you pure z80 missing opcodes soon.

**Comment by hlide** [comment]
There is another issue: RASM supports multi-instruction per line through `:` separator.

For instance:
```
LD D,(HL):INC HL ; b0 = ++*byteptr
LD E,(HL):INC HL ; b1 = ++*byteptr
LD B,(HL):INC HL ; b2 = ++*byteptr
LD C,(HL):INC HL ; b3 = ++*byteptr
...
```

**Pull request merged**
